server:
  port: 6001

spring:
  application:
    name: study-springboot-velocity

logging:
  level:
    root: INFO                    #默认的日志级别
  file: log/study-springboot-velocity.log #生成日志文件的位置 e:/study-springboot-velocity.log
